version: '3.9'
services:
  app:
    build: .
    container_name: the-agency
    volumes:
      - .:/app
    environment:
      - SQLITE_PATH=the_agency.db
    command: python interfaces/cli_interface.py
